[TASK] Let built fail if uncommited changes exist

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -79,7 +79,10 @@ jobs:
         yarn stylelint
     - name: Status
       run: |
-        git status
+        if [[ `git status --porcelain` ]]; then
+          echo "::error Uncommitted changes"
+          exit 1
+        fi
 
   deployment:
     name: Deployment
